# Wavy
#
# Copyright (c) 2019-2020 Jeron Aldaron Lau
# 
# Licensed under the Apache License, Version 2.0, <LICENSE-APACHE or
# https://apache.org/licenses/LICENSE-2.0>, or the Zlib License, <LICENSE-ZLIB
# or http://opensource.org/licenses/Zlib>, at your option. This file may not be
# copied, modified, or distributed except according to those terms.

[package]
name = "wavy"
version = "0.4.0"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
license = "Apache-2.0 OR Zlib"

description = "Asynchronous cross-platform real-time audio recording & playback."
repository = "https://github.com/libcala/wavy"
documentation = "https://docs.rs/wavy"
homepage = "https://github.com/libcala/wavy/blob/master/CHANGELOG.md"
include = ["Cargo.toml", "README.md", "LICENSE-ZLIB", "LICENSE-APACHE", "src/*"]
categories = ["game-engines", "hardware-support", "multimedia", "multimedia::audio", "os"]
keywords = ["audio", "realtime", "cross-platform", "record", "play"]
readme = "README.md"
edition = "2018"

[badges]
travis-ci = { repository = "libcala/wavy" }
is-it-maintained-issue-resolution = { repository = "libcala/wavy" }
is-it-maintained-open-issues = { repository = "libcala/wavy" }
maintenance = { status = "actively-developed" }

[dependencies.fon]
version = "0.2"

# Use cala_core to support all of: wasm-pack, cargo-cala-web and cargo-web
[target.'cfg(target_arch = "wasm32")'.dependencies.cala_core]
version = "0.1"
optional = true

[target.'cfg(all(not(target_arch = "wasm32"), any(target_os = "linux", target_os = "android")))'.dependencies]
smelling_salts = "0.1"

[dev-dependencies]
pasts = "0.4"
twang = "0.3"

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-unknown-linux-gnu"

[features]
default = []
docs-rs = []
cala = ["cala_core/cala"]
stdweb = ["cala_core/stdweb"]
wasm-bindgen = ["cala_core/wasm-bindgen"]

# [replace]
# "fon:0.1.0" = { path = "../fon" }
