# Wavy
#
# Copyright (c) 2019-2020 Jeron Aldaron Lau
# 
# Licensed under the Apache License, Version 2.0, <LICENSE-APACHE or
# https://apache.org/licenses/LICENSE-2.0>, or the Zlib License, <LICENSE-ZLIB
# or http://opensource.org/licenses/Zlib>, at your option. This file may not be
# copied, modified, or distributed except according to those terms.

[package]
name = "wavy"
version = "0.5.0"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
license = "Apache-2.0/Zlib"

description = """
Asynchronous cross-platform real-time audio recording & playback.
"""
repository = "https://github.com/libcala/wavy"
documentation = "https://docs.rs/wavy"
homepage = "https://github.com/libcala/wavy/blob/master/CHANGELOG.md"
include = ["Cargo.toml", "README.md", "LICENSE-ZLIB", "LICENSE-APACHE", "src/*"]
categories = [
    "game-engines", "hardware-support", "multimedia", "multimedia::audio", "os"
]
keywords = ["audio", "realtime", "cross-platform", "record", "play"]
readme = "README.md"
edition = "2018"

# For all platforms
[dependencies.fon]
version = "0.2"

# For Linux and Android
[target.'cfg(all(not(target_arch = "wasm32"), any(target_os = "linux", target_os = "android")))'.dependencies.smelling_salts]
version = "0.1"

# For Web Assembly
[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3"
features = [
    "AudioContext",
    "AudioContextOptions",
    "AudioNode",
    "AudioDestinationNode",
    "ScriptProcessorNode",
    "AudioProcessingEvent",
    "AudioBuffer",
    "MediaStreamConstraints",
    "Window",
    "Navigator",
    "MediaDevices",
    "MediaStream",
    "MediaStreamAudioSourceNode",
    "MediaStreamAudioSourceOptions",
]
[target.'cfg(target_arch = "wasm32")'.dependencies.wasm-bindgen]
version = "0.2"

# Examples
[dev-dependencies]
pasts = "0.6"
twang = "0.4"

# Default to x86 64-bit Linux
[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-unknown-linux-gnu"

# Uncomment to replace dependencies with experimental versions.
# [replace]
# "fon:0.2.0" = { path = "../fon" }
